  <div id="submenu_left">
<!-- 
   <ul>
        <li><a href="projects_potato_chr6.php">RH Chromosome 6</a>
        <ul>
            <li><a href="projects_potato_bacs_summary.php">RH BACs Summary</a>
                <ul>
                    <li><a href="projects_potato_bacs_details.php">RH BACs Details</a>          
                </ul>
            </li>
        </ul>
        </li>
        <li><a href="projects_potato_phureja.php">Phureja DM</a></li>
    </ul>
-->
  </div>
  
  
  <div id="submenu_content">
  <!-- InstanceBeginEditable name="GenomesBody" -->
    <h1>Potato Genome Sequencing</h1>
<p>
To improve our understanding of potato, we are participating in the International
 <a href="http://www.potatogenome.net">Potato Genome Sequencing Consortium</a> (PGSC).
 The PGSC is engaged in sequencing two potato species: the heterozygous diploid heterozygous <em>S. tuberosum</em>
 cultivar, RH89-039-16 (RH), and the doubled monoploid <em>S. phureja</em> clone DM1-3 516R44 (DM). To date, we have
 contributed to the generation of significant RH
 genome sequence through (1) end sequencing of the RHPOTKEY library and (2) in sequencing of RH BACs, primarily from chromosome 6.
</p>
<p>
 With respect to the DM genome, we have generated end sequence from fosmid clones and DM BAC clones. These sequences are currently
 being combined with whole genome sequences from DM generated by other PGSC members using the 454 pyrosequencing platform and the
 Illumina sequencing-by-synthesis platform to generate a high quality draft genome sequence for potato. To aid in the annotation
 of the potato genome, we have initiated a comprehensive transcriptome project for the DM clone.
</p>
<h3>Project Resources</h3>
<!--            <p>Track the BAC sequencing status on our <a href="projects_potato_bacs_summary.php">BAC summary page</a>.</p> -->
      <p>BAC and BAC end sequences are <a href="ftp://ftp.plantbiology.msu.edu/pub/sgr/potato/">available for download from our ftp site</a>.</p>
      <p>Annotation of the potato BAC sequences is accessible through our <a href="/cgi-bin/gbrowse/solanaceae/">Solanaceae comparative genome database</a>.
      <p>Analyses of the potato BAC and BAC end sequences can be found through our <a href="/analyses">Analyses/Tools</a> page. 
      <!-- InstanceEndEditable -->  </div>
